name: ibvse
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.12.0
  - torchvision=0.13.0
  - torchaudio=0.12.0
  - cudatoolkit=11.3
  - numpy=1.23.0
  - tqdm=4.64
  - future=0.18.2
  - tensorboard>=2.0.0
  - pandas=1.4.3
  - faiss-gpu=1.7.2
  - imageio=2.19.3
  - scikit-learn=1.1.1
  - scikit-image=0.19.3
  - plotly=5.9.0
  - optuna=2.10.0
  - hnswlib=0.6.2
  - python-annoy=1.17.0
  - pip=22.1.2
  - pip:
      - argparse==1.4.0
      - opencv-python==4.6.0.66
      - PyQt5==5.15.7
      - matplotlib==3.5.2
      - mega.py==1.0.8
